# Use for development of routing systems without requiring gpu servers

services:
  server-1:
    build:
      context: .
      dockerfile: router/dev/fakeserver/Dockerfile
    container_name: fakeserver-container1
    ports:
      - "8000:8000"

  server-2:
    build:
      context: .
      dockerfile: router/dev/fakeserver/Dockerfile
    container_name: fakeserver-container2
    ports:
      - "8001:8000"

  router:
    build:
      context: .
      dockerfile: router/Dockerfile
    container_name: router
    ports:
      - "7999:7999"
    depends_on:
      - server-1
      - server-2

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "7998:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./router/dev/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - router
