global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'vllm-backend-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-1:8000']
        labels:
          backend: 'gpu-0'

  - job_name: 'vllm-backend-2'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-2:8000']
        labels:
          backend: 'gpu-1'

  - job_name: router
    static_configs:
    - targets: ['router:7999']
      labels:
        component: 'router'
